arch:
  - amd64
  - ppc64le
os: linux
dist: bionic
language: generic
services:
- docker
deploy:
- provider: script
  script: bash hack/deploy.sh
  cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(ocp-.*|master)$
